name: Tireless Hope
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12743
title: Tireless Hope
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a6b619'
    - '#2d2d2d'
    - '#f2f2f2'
    - '#00bfd3'
    - '#f65836'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
